#include "rng/rng.h"
#include <stdio.h>

#define X_LIM 8.0
#define Y_LIM 1.0
#define LAYER_COUNT (1u << RNG_ZIG_LAY_BITS)
#define SEARCH_ROUNDS 64

int main(void) {
  double lay_xs_loc[LAYER_COUNT + 1] = {X_LIM};
  double lay_ys_loc[LAYER_COUNT + 1] = {0.0};

  double area_min = 0.0, area_max = X_LIM * Y_LIM / LAYER_COUNT;

  for (size_t i = 0; i < SEARCH_ROUNDS; ++i) {
    double area = (area_min + area_max) * 0.5;

    // Figure out if our area is too big or too small
    double final_height = 0.0;
    for (size_t j = 0; j < LAYER_COUNT; ++j) {
      double lay_width = lay_xs_loc[j];
      double lay_height = area / lay_width;

      lay_ys_loc[j + 1] = lay_ys_loc[j] + lay_height;

      final_height = lay_ys_loc[j + 1];
      if (final_height > Y_LIM) {
        break;
      }

      double x = prob_dens_inv(lay_ys_loc[j + 1]);
      x = x > X_LIM ? X_LIM : x;
      lay_xs_loc[j + 1] = x;
    }

    // Update the area bounds
    if (final_height > Y_LIM) {
      area_max = area;
    } else {
      area_min = area;
    }
  }

  for (size_t j = 0; j < LAYER_COUNT; ++j) {
    double lay_width = lay_xs_loc[j];
    double lay_height = area_max / lay_width;

    lay_ys_loc[j + 1] = lay_ys_loc[j] + lay_height;

    double y = lay_ys_loc[j + 1];
    y = y > Y_LIM ? Y_LIM : y;
    double x = prob_dens_inv(y);
    x = x > X_LIM ? X_LIM : x;
    lay_xs_loc[j + 1] = x;
  }

  // Clean up the final point
  lay_xs_loc[LAYER_COUNT] = 0.0;
  lay_ys_loc[LAYER_COUNT] = Y_LIM;

  // Write the layers to stdout
  printf("/* Procedurally generated by %s */\n\n", __FILE__);
  printf("const float lay_xs[] = {\n");
  for (size_t i = 0; i < LAYER_COUNT + 1; ++i) {
    printf("%a,\n", (float)lay_xs_loc[i]);
  }
  printf("};\n\n");
  printf("const float lay_ys[] = {\n");
  for (size_t i = 0; i < LAYER_COUNT + 1; ++i) {
    printf("%a,\n", (float)lay_ys_loc[i]);
  }
  printf("};\n");

  return 0;
}
